# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170326_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyewitnessStimuli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(60, 60), (80, 80), (100, 100)])),
                ('lineup_race', models.CharField(choices=[('B', 'black'), ('W', 'white')], max_length=1)),
                ('lineup_number', models.IntegerField(choices=[('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('B4', 'B4'), ('B5', 'B5'), ('B6', 'B6'), ('W1', 'W1'), ('W2', 'W2'), ('W3', 'W3'), ('W4', 'W4'), ('W5', 'W5'), ('W6', 'W6')])),
                ('category', models.CharField(choices=[('O1', 'O1'), ('Omany', 'Omany'), ('R', 'R'), ('U1', 'U1'), ('F', 'F')], max_length=10)),
                ('statement', models.TextField(max_length=100)),
                ('chosen_face', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('lineup_order', models.CharField(max_length=14)),
            ],
        ),
    ]
