# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170329_1254'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eyewitnessstimuli',
            managers=[
            ],
        ),
    ]
