# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20170329_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.IntegerField(blank=True, choices=[(60, 60), (80, 80), (100, 100)]),
        ),
    ]
